services:
  database:
    image: mysql
    container_name: users-db
    build: Dockerfile.database
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"